# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia 
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("ExportWebAssembly"); Pkg.test("ExportWebAssembly"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'ENV["DOCUMENTER_DEBUG"] = "true"; cd(Pkg.dir("ExportWebAssembly", "docs")); include("make.jl")'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("ExportWebAssembly")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ExportWebAssembly")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
